various fixes

diff --git a/build_debian b/build_debian
--- a/build_debian
+++ b/build_debian
@@ -2,8 +2,8 @@
 
 set -e
 
-# Display usage information
-usage() { 
+# Display USAGE information
+USAGE() { 
 	printf "%s\n" "Usage: sudo $0 [n[net]] | [f[full]]" \
 		"Use [n[net]] for a net-install" \
 		"Use [f[full]] for a DVD install" \
@@ -11,64 +11,72 @@ usage() {
 }
 
 # Check if no arguments are provided, display usage
-[ $# -eq 0 ] && usage
+[ $# -eq 0 ] && USAGE
 
 # Check for required installed programs
-progrms=(
+PROGRAMS=(
     xorriso
     aria2c
     curl
     gpg
 )
 
-for var in "${progrms[@]}"; do
-    if ! command -v "$var" &> /dev/null; then
-        echo "$var not found. Please install"
+for PROGRAM in "${PROGRAMS[@]}"; do
+    if ! command -v "$PROGRAM" &> /dev/null; then
+        echo "$PROGRAM not found. Please install"
         exit 1
     fi
 done
 
 # Function to download and verify ISO
-download_and_verify_iso() {
-    cd debian
+DOWNLOAD_ISO() {
+
+    [[ -d ./debian ]] || mkdir -p ./debian
+
     # Download newest iso unless local copy exists
-    for file in $(curl -s  "$http_iso_dir/" |
+    for FILE in $(curl -s  "$HTTP_ISO_DIR/" |
         grep href |
         sed 's/.*href="//' |
         sed 's/".*//' |
         grep -E 'debian-[0-9]'); do
             aria2c -c  --auto-file-renaming=false  --allow-overwrite=true \
-                "$http_iso_dir/$file"
+                --dir=./debian "$HTTP_ISO_DIR/$FILE"
     done
 
-    # Download SHA512SUMS and SHA512SUMS.sign
-    curl --output SHA512SUMS "$http_iso_dir/SHA512SUMS"
-    curl --output SHA512SUMS.sign "$http_iso_dir/SHA512SUMS.sign"
+    # Since SHA512SUMS file name never changes, always download new
+    curl --output ./debian/SHA512SUMS "$HTTP_ISO_DIR/SHA512SUMS"
+    curl --output ./debian/SHA512SUMS.sign "$HTTP_ISO_DIR/SHA512SUMS.sign"
+
+}
+
+VERIFY_ISO() {
+
 
     # Check signatures
     gpg --keyserver keyring.debian.org --recv-key 0xDA87E80D6294BE9B
-    if gpg --verify SHA512SUMS.sign SHA512SUMS; then
+    if gpg --verify ./debian/SHA512SUMS.sign ./debian/SHA512SUMS; then
         echo "Debian signature matches"
     else
         echo "Signature mismatch. Quitting..."
-        echo "Please remove $debian_iso SHA512SUMS.sign SHA512SUMS"
+        echo "Please remove $DEBIAN_ISO SHA512SUMS.sign SHA512SUMS from debian dir"
         exit 1
     fi
 
     # Check sha512sum
-    if echo "$debian_iso" | sha512sum -c --ignore-missing <(cat SHA512SUMS); then
+    if echo "$DEBIAN_ISO" | sha512sum -c --ignore-missing \
+        <(sed 's|^\(.*\) \(debian-.*\)|\1 \./debian/\2|' ./debian/SHA512SUMS); then
         echo "SHA512SUM matches"
     else
         echo "SHA512SUM does not match. quitting"
-        echo "Please remove $debian_iso and SHA512SUMS"
+        echo "Please remove $DEBIAN_ISO and SHA512SUMS from debian dir"
         exit 1
     fi
-    cd -
+
 }
 
 # Function to build Debian ISO
-build_debian_iso() {
-    xorriso -osirrox on -indev "./debian/$debian_iso" -extract / ./debian/isofiles
+BUILD_DEBIAN_ISO() {
+    xorriso -osirrox on -indev "./debian/$DEBIAN_ISO" -extract / ./debian/isofiles
 
     # Make .iso writeable and create scrips folder for cdrom dir
     chmod +w -R ./debian/isofiles/
@@ -88,46 +96,47 @@ build_debian_iso() {
 
     chmod -w -R ./debian/isofiles/
 
-    new_files=./debian/isofiles
-    new_iso=./"debian-$(echo "$debian_iso" | \
-        cut -d- -f2)-amd64-$(echo "$debian_iso" | \
+    NEW_FILES=./debian/isofiles
+    NEW_ISO=./"debian-$(echo "$DEBIAN_ISO" | \
+        cut -d- -f2)-amd64-$(echo "$DEBIAN_ISO" | \
         cut -d- -f4 | cut -d. -f1)-btrfs-modified.iso"
-    mbr_template=./debian/isohdpfx.bin
+    MBR_TEMPLATE=./debian/isohdpfx.bin
 
     # Extract MBR template file to disk
-    dd if="./debian/$debian_iso" bs=1 count=432 of="$mbr_template"
+    dd if="./debian/$DEBIAN_ISO" bs=1 count=432 of="$MBR_TEMPLATE"
 
     # Create the new ISO image
     xorriso -as mkisofs \
        -r -V 'Debian modified iso' \
-       -o "$new_iso" \
+       -o "$NEW_ISO" \
        -J -J -joliet-long -cache-inodes \
-       -isohybrid-mbr "$mbr_template" \
+       -isohybrid-mbr "$MBR_TEMPLATE" \
        -b isolinux/isolinux.bin \
        -c isolinux/boot.cat \
        -boot-load-size 4 -boot-info-table -no-emul-boot \
        -eltorito-alt-boot \
        -e boot/grub/efi.img \
        -no-emul-boot -isohybrid-gpt-basdat -isohybrid-apm-hfsplus \
-       "$new_files"
+       "$NEW_FILES"
 }
 
 # Main script logic
 case $1 in
     n|net)
-        http_iso_dir="https://cdimage.debian.org/debian-cd/current/amd64/iso-cd"
-        # Use a for loop instead of ls and grep
-        debian_iso=$(find debian -maxdepth 1 -type f -name 'debian-*-amd64-netinst.iso' -printf '%P\n' | sort -r | head -n1 | cut -d/ -f3)
-        download_and_verify_iso
-        build_debian_iso
+        HTTP_ISO_DIR="https://cdimage.debian.org/debian-cd/current/amd64/iso-cd" 
+        DOWNLOAD_ISO
+        DEBIAN_ISO=$(find debian -maxdepth 1 -type f -name 'debian-*-amd64-netinst.iso' -printf '%P\n' | sort -r | head -n1)
+        VERIFY_ISO
+        BUILD_DEBIAN_ISO
         ;;
     f|full)
-        http_iso_dir="https://cdimage.debian.org/debian-cd/current/amd64/iso-dvd"
-        debian_iso=$(find debian -maxdepth 1 -type f -name 'debian-*-amd64-DVD-*.iso' -printf '%P\n' | sort -r | head -n1 | cut -d/ -f3)
-        download_and_verify_iso
-        build_debian_iso
+        HTTP_ISO_DIR="https://cdimage.debian.org/debian-cd/current/amd64/iso-dvd"
+        DOWNLOAD_ISO
+        DEBIAN_ISO=$(find debian -maxdepth 1 -type f -name 'debian-*-amd64-DVD-*.iso' -printf '%P\n' | sort -r | head -n1)
+        VERIFY_ISO
+        BUILD_DEBIAN_ISO
         ;;
     h|*)
-        usage 
+        USAGE 
         ;;
 esac
